#!/bin/bash

if [ -f cloud-init-slimhub.yaml ]; then
  rm cloud-init-slimhub.yaml
fi
# Base of init is just python3
tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
#cloud-config
package_upgrade: true
packages:
  - python3-dev
  - python3-pip
EOT
# Add back after debug
#  - texlive-full # for notebook rendering

# add the config files and setup ssl certificates and https
tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
write_files:
  - path: /opt/configs/setup_0_tljh
    content: |
      tljh-config set user_environment.default_app jupyterlab
      tljh-config set https.enabled true
      tljh-config set https.letsencrypt.email mathias.louboutin@gmail.com
      tljh-config add-item https.letsencrypt.domains $1
      tljh-config set services.cull.timeout 1800
      tljh-config set limits.cpu 4
      tljh-config set limits.memory 8G
      while read -r line
      do
        tljh-config add-item users.allowed \$line
      done < /opt/configs/users
      tljh-config reload
EOT

# Check if there is credentials for mecurvelet
if [ ! -z $2 ]; then
  creds=$(echo $2 | sed 's/\$/\\$/')
  echo $creds
tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
  - path: /opt/configs/setup_99_mecurvelet
    content: |
      julia --project=\$julia_global_env -e 'deleteat!(DEPOT_PATH, [1,3]);using Pkg; Pkg.add(url="https://$creds@github.gatech.edu/SLIM/MECurvelets.jl.git");Pkg.precompile()'
EOT
fi

# Add all users
tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
  - path: /opt/configs/users
    content: |
$(python3 read_csv.py | sed 's/^/      /')
EOT

# Installs such as julia and python libs
for f in configs/*; do
  if [ -f "$f" ]; then
    tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
  - path: /opt/$f
    content: |
$(cat $f | sed 's/^/      /')
EOT
  fi
done

# Command list for cloud init
tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
runcmd:
  - curl -L https://tljh.jupyter.org/bootstrap.py | python3 - --admin slimadmin
  - for f in /opt/configs/setup*; do bash \$f; done
EOT
