#!/bin/bash

if [ -f cloud-init-slimhub.yaml ]; then
  rm cloud-init-slimhub.yaml
fi
# Base of init is just python3
tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
#cloud-config
package_upgrade: true
packages:
  - python3-dev
  - python3-pip
  - texlive-full # for notebook rendering
EOT

# add the config files
tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
write_files:
EOT


for f in configs/*; do
  if [ -f "$f" ]; then
    tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
  - path: /opt/install_libs/$f
    content: |
$(cat $f | sed 's/^/      /')
EOT
  fi
done


tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
runcmd:
  - curl -L https://tljh.jupyter.org/bootstrap.py | sudo python3 - --admin slimadmin
EOT
for f in configs/*; do
  if [ -f "$f" ]; then
      tee -a cloud-init-slimhub.yaml > /dev/null <<-EOT
  - bash /opt/install_libs/$f
EOT
  fi
done