#!/bin/bash

hname=slimhub
nuser=2

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--hubname)
      hname="$2"
      shift # past argument
      shift # past value
      ;;
    -n|--nuser)
      nuser="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      shift # past argument
      shift # past value
      ;;
  esac
done

rname=${hname}RG
let "mem = 32 + $nuser * 6 / 10"

echo "Starting a JupyterHub $hname for $nuser users with $mem Gb of disk space"

# Creates an azure vm with the littlest jupytehub for tutorials
# Size is defined based on number odf expected users
# run as `./makevm.sh nusers`

# generate the cloud-init setup file
bash cloud_init

# create separate resource group for easy cleanup

az group create -l eastus -n $rname

az vm create --resource-group $rname \
  --name $hname \
  --size Standard_F8s_v2 \
  --image Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest \
  --admin-username slimazure \
  --generate-ssh-keys \
  --location eastus \
  --os-disk-size-gb $mem \
  --custom-data cloud-init-slimhub.yaml

# Open http and https ports for browser access
az vm open-port \
    --resource-group $rname \
    --name $hname \
    --port 80,443

# create cleanup file
if [ -f cleanup_slimhub ]; then
  rm cleanup_slimhub
fi;

tee -a cleanup_slimhub > /dev/null <<EOT
#!/bin/bash
az group delete -n $rname --yes
EOT

chmod +x cleanup_slimhub
