#!/bin/bash
#
# Install thepython depedencies
source /opt/tljh/user/bin/activate
pip3 install -U pip
# save current dir
dir=$PWD
# Install devito in home directory
cd $HOME
git clone https://github.com/devitocodes/devito
cd devito
# activate the global environment
sudo -E pip install -e .[extras]

# Make examples available
cp -r examples/seismic/tutorials /etc/skel/devito_seismic_tutorials

source /opt/tljh/user/bin/deactivate
# get back
cd $dir
